version: "3.5"

services:
  web:
    container_name: web
    image: bref/fpm-dev-gateway
    ports:
      - '8080:80'
    volumes:
      - .:/var/task
    depends_on:
      - php
    environment:
      HANDLER: public/index.php
      DOCUMENT_ROOT: public
  php:
    container_name: php
    image: bref/php-81-fpm-dev
    environment:
      SERVERLESS_STAGE: local
    volumes:
      - .:/var/task:ro
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
  
  dynamodb_admin:
    container_name: dynamodb_admin
    image: aaronshaf/dynamodb-admin
    ports:
      - '8001:8001'
    environment:
      AWS_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
      DYNAMO_ENDPOINT: http://dynamodb:8000

  console:
    container_name: console
    image: bref/php-81
    volumes:
      - .:/var/task:ro
    entrypoint: php