service: bref-php-3

provider:
  name: aws
  region: eu-west-1
  runtime: provided.al2
  iam:
    role:
      statements:
        - Sid: "ListAndDescribe"
          Effect: "Allow"
          Action:
            - dynamodb:List*
            - dynamodb:DescribeReservedCapacity*
            - dynamodb:DescribeLimits
            - dynamodb:DescribeTimeToLive
          Resource: "*"
          
        - Sid: "AllowElephpants"
          Effect: "Allow"
          Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/elephpant"

plugins:
  - ./vendor/bref/bref
  - serverless-lift

functions:
  api:
    handler: public/index.php
    description: ""
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-81-fpm}
    events:
      - httpApi: "*"
    environment:
      SERVERLESS_STAGE: dev

  console:
    handler: bin/console
    layers:
      - ${bref:layer.php-81}
      - ${bref:layer.console}

constructs:
  website:
    type: server-side-website
    assets:
      "/assets/*": "public/assets"
resources:
  Resources:
    elephpantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: elephpants-3
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: N
        BillingMode: PAY_PER_REQUEST
        

# Exclude files from deployment
package:
  patterns:
    - "!node_modules/**"
    - "!tests/**"
