service: bref-php-5

provider:
  name: aws
  region: eu-west-1
  runtime: provided.al2
  iam:
    role:
      statements:
        - Sid: "ListAndDescribe"
          Effect: "Allow"
          Action:
            - dynamodb:List*
            - dynamodb:DescribeReservedCapacity*
            - dynamodb:DescribeLimits
            - dynamodb:DescribeTimeToLive
          Resource: "*"
          
        - Sid: "AllowElephpants"
          Effect: "Allow"
          Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/elephpants-*"

        - Sid: "AllowElephpantsS3"
          Effect: "Allow"
          Action:
          - s3:PutObject
          - s3:GetObject
          - s3:DeleteObject
          - s3:PutObjectAcl
          - s3:ListObjects
          Resource: !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref ElephpantsBucket
              - /*

plugins:
  - ./vendor/bref/bref
  - serverless-lift

functions:
  frontend:
    handler: public/index.php
    description: ""
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-81-fpm}
    events:
      - httpApi: "*"
    environment:
      SERVERLESS_STAGE: dev
      ELEPHANTS_BUCKET: !Ref ElephpantsBucket

  console:
    handler: bin/console
    layers:
      - ${bref:layer.php-81}
      - ${bref:layer.console}

constructs:
  website:
    type: server-side-website
    assets:
      "/assets/*": "public/assets"

resources:
  Resources:
    ElephpantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: elephpants-5
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: N
        BillingMode: PAY_PER_REQUEST
    ElephpantsBucket:
        Type: 'AWS::S3::Bucket'
        Properties:
          AccessControl: PublicRead
          WebsiteConfiguration:
            IndexDocument: index.html
            ErrorDocument: error.html
          CorsConfiguration:
            CorsRules:
              - AllowedOrigins:
                  - '*'
                AllowedHeaders:
                  - '*'
                AllowedMethods:
                  - GET
                  - POST
                MaxAge: 3000
        DeletionPolicy: Retain
    ElephpantsBucketPolicy:
      Type: 'AWS::S3::BucketPolicy'
      Properties:
        PolicyDocument:
          Id: ElephpantBucketPolicy
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref ElephpantsBucket
                  - /*
        Bucket: !Ref ElephpantsBucket
# Exclude files from deployment
package:
  patterns:
    - "!node_modules/**"
    - "!tests/**"
